#!/usr/bin/env python3
"""Regenerate the badge table in README.md between the BADGES markers.

Pulls *live* values so the badges never drift from reality:

* DuckDB extension commit hashes  -> `duckdb_extensions()` (after INSTALL).
  Note DuckDB reports a git COMMIT HASH, not a release tag.
* DuckDB engine version            -> the installed `duckdb` module.
* dbt-core / dbt-duckdb versions    -> parsed from requirements.txt.

The CI / Elementary entries are GitHub Actions status badges (already
live). Run locally with `python scripts/update_extension_badges.py`, or
let `.github/workflows/badges.yml` run it on push + weekly schedule and
commit any change. Exits non-zero only on real errors; a no-op (nothing
changed) is success.
"""
from __future__ import annotations

import pathlib
import re
import sys
from urllib.parse import quote

import duckdb

REPO = "oluies/dbt-duckdb-trading-calendar"
ROOT = pathlib.Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
REQUIREMENTS = ROOT / "requirements.txt"

START = "<!-- BADGES:START -->"
END = "<!-- BADGES:END -->"
# Extensions this project loads, in profiles.yml order, with repo + role.
EXTENSIONS = [
    ("httpfs", "core", "FFF000", "duckdb", "black",
     "https://duckdb.org/docs/stable/core_extensions/httpfs/overview",
     "core extension — reads the remote Parquet over HTTPS"),
    ("azure", "core", "FFF000", "duckdb", "black",
     "https://duckdb.org/docs/stable/core_extensions/azure",
     "core extension — Azure blob storage access for the Open Datasets feed"),
    ("mssql", "community", "blue", "microsoftsqlserver", "white",
     "https://github.com/hugr-lab/mssql-extension",
     "community extension — `ATTACH`es SQL Server so dbt writes the marts there"),
]


def shield(label: str, message: str, color: str, logo: str, logo_color: str) -> str:
    """Build a shields.io static-badge URL (dashes escaped as `--`)."""
    seg = lambda s: quote(s.replace("-", "--"), safe="")
    return (f"https://img.shields.io/badge/{seg(label)}-{seg(message)}-{color}"
            f"?logo={logo}&logoColor={logo_color}")


def md_badge(alt: str, badge_url: str, link: str) -> str:
    return f"[![{alt}]({badge_url})]({link})"


def req_version(package: str) -> str:
    for line in REQUIREMENTS.read_text().splitlines():
        m = re.match(rf"^{re.escape(package)}==([^\s;]+)", line.strip())
        if m:
            return m.group(1)
    raise SystemExit(f"could not find pinned version for {package} in requirements.txt")


def extension_hashes() -> dict[str, str]:
    con = duckdb.connect()
    con.execute("INSTALL httpfs; INSTALL azure; INSTALL mssql FROM community;")
    rows = con.execute(
        "SELECT extension_name, extension_version FROM duckdb_extensions() "
        "WHERE extension_name IN ('httpfs', 'azure', 'mssql')"
    ).fetchall()
    return {name: (ver or "unknown") for name, ver in rows}


def build_table() -> str:
    dbt_core = req_version("dbt-core")
    dbt_duckdb = req_version("dbt-duckdb")
    engine = duckdb.__version__
    hashes = extension_hashes()

    actions = f"https://github.com/{REPO}/actions"
    rows: list[tuple[str, str]] = [
        (md_badge("CI", f"{actions}/workflows/ci.yml/badge.svg",
                  f"{actions}/workflows/ci.yml"),
         "**CI** — `dbt build` + test against SQL Server 2022 on every push / PR"),
        (md_badge("Elementary report", f"{actions}/workflows/elementary.yml/badge.svg",
                  f"{actions}/workflows/elementary.yml"),
         "**Elementary** — scheduled OSS data-observability HTML report"),
        (md_badge("dbt-core", shield("dbt-core", dbt_core, "FF694B", "dbt", "white"),
                  "https://github.com/dbt-labs/dbt-core"),
         f"**dbt-core** `{dbt_core}` — pinned in `requirements.txt`"),
        (md_badge("dbt-duckdb", shield("dbt-duckdb", dbt_duckdb, "FF694B", "dbt", "white"),
                  "https://github.com/duckdb/dbt-duckdb"),
         f"**dbt-duckdb** adapter `{dbt_duckdb}` — pinned in `requirements.txt`"),
        (md_badge("DuckDB", shield("DuckDB", f"v{engine}", "FFF000", "duckdb", "black"),
                  "https://duckdb.org"),
         f"**DuckDB** engine `v{engine}`"),
    ]
    for name, repo, color, logo, logo_color, link, role in EXTENSIONS:
        h = hashes.get(name, "unknown")
        rows.append((
            md_badge(f"ext: {name}",
                     shield(f"ext: {name}", h, color, logo, logo_color), link),
            f"**{name}** {role} — installed `{h}`",
        ))

    body = "\n".join(f"| {badge} | {note} |" for badge, note in rows)
    return "| Badge | What it tracks |\n| --- | --- |\n" + body


def main() -> int:
    table = build_table()
    note = (f"{START}\n"
            "<!-- auto-generated by scripts/update_extension_badges.py — "
            "do not edit between these markers -->\n")
    block = f"{note}{table}\n{END}"

    text = README.read_text()
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(f"BADGES markers not found in {README}")
    updated = pattern.sub(lambda _: block, text)

    if updated == text:
        print("Badges already up to date.")
        return 0
    README.write_text(updated)
    print("README badge table updated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
